
POST http://localhost:3000/api/admin/login
content-type: application/json

{
    "username": "admin",
    "password": "password"
}
###
POST http://localhost:3000/api/admin/logout
###

GET http://localhost:3000/api/admin
###
GET http://localhost:3000

###
POST http://localhost:3000/api/admin/create
content-type: application/json

{
    "username": "admi@gmail.com",
    "password": "ddd"
}

###
POST http://localhost:3000/api/employee/create
Content-Type: application/json

{
    "email":"abcd@gmail.com",
    "password": "password",
    "firstName": "deptrai",
    "lastName": "deptrai",
    "dateOfBirth": "10/10/2010",
    "address": "and, sjs, đmm",
    "phone": "0238492093",
    "roleId": 1
}

###
POST http://localhost:3000/api/employee/login
Content-Type: application/json

{
    "email": "abc@123.vn",
    "password": "password"
}
###
POST http://localhost:3000/api/employee/logout

###
GET http://localhost:3000/api/employee

###
POST http://localhost:3000/api/employee/create
Content-Type: application/json

{
    "email":"employee@123.vn",
    "password": "password",
    "firstName": "deptrai",
    "lastName": "deptrai",
    "dateOfBirth": "10/10/2010",
    "address": "and, sjs, đmm",
    "phone": "0999299352",
    "roleId": 2,
    "branchId": 2
}

###
GET http://localhost:3000/api/role
###
GET http://localhost:3000/api/role/1

###
POST http://localhost:3000/api/employee/2/update
Content-Type: application/json

{
    "firstName": "occho"
}

###
POST http://localhost:3000/api/employee/8/delete

###
GET http://localhost:3000/api/getData

###
POST http://localhost:3000/api/branch/create
Content-Type: application/json

{
    "managerId":3,
    "branchName":"Que Vo 1",
    "province": "Bac Ninh",
    "district":"Que Vo",
    "detailAddress": "Que Vo 1",
    "isHub":1
}
###
POST http://localhost:3000/api/branch/create
Content-Type: application/json

{
    "managerId":1,
    "branchName":"Que Vo 2",
    "province": "Bac Ninh",
    "district":"Que Vo",
    "detailAddress": "Que Vo 2",
    "hubId": 13,
    "isHub":0
}

###
POST http://localhost:3000/api/employee/create
Content-Type: application/json

{
    "email":"employe@gmail.vn",
    "password": "password",
    "firstName": "deptrai",
    "lastName": "deptrai",
    "dateOfBirth": "10/10/2010",
    "address": "and, sjs, đmm",
    "phone": "0999294952",
    "branchId": 13,
    "roleId": 5
}

###
POST http://localhost:3000/api/employee/create
Content-Type: application/json

{
    "email":"employee@gmail.com",
    "password": "password",
    "firstName": "deptrai",
    "lastName": "deptrai",
    "dateOfBirth": "10/10/2010",
    "address": "and, sjs, đmm",
    "phone": "0999299359",
    "branchId": 14,
    "roleId":4
}